apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: test
          image: busybox
          command: ["echo", "Hello Jenkins X"]

